/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
  [k: string]: unknown;
}
export type ExecuteMsg = ExecMsg;
export type ExecMsg = {
  split: {
    amounts: [Addr, Uint128, string][];
    [k: string]: unknown;
  };
} | {
  withdraw_remains: {
    [k: string]: unknown;
  };
};
export type Addr = string;
export type Uint128 = string;
export type QueryMsg = QueryMsg1;
export type QueryMsg1 = {
  admin_list: {
    [k: string]: unknown;
  };
};
export interface AdminListResp {
  admins: string[];
  [k: string]: unknown;
}